projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - graphql/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react-native
        maxDepth: 8
extensions:
  amplify:
    version: 3
